# Some portions copied from playbook-dispatcher
version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=32181
      - ZOOKEEPER_SERVER_ID=1

  kafka:
    image: confluentinc/cp-kafka
    ports:
      - '29092:29092'
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:32181
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true

  minio:
    image: minio/minio
    command: server /data --console-address ":10000"
    volumes:
      # These vars are defined in .env
      # These are configurable
      # Ensure the directories exist prior to running this file
      - minio_conf:/root/.minio:Z
      - minio_data:/data:Z
    ports:
      - '9000:9000'
      - '10000:10000'
    environment:
      - MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY=$MINIO_SECRET_KEY

  minio-createbuckets:
    image: minio/mc
    depends_on:
      - minio
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 "$MINIO_ACCESS_KEY" "$MINIO_SECRET_KEY" || exit 1;
      /usr/bin/mc mb --ignore-existing myminio/insights-upload-perma;
      /usr/bin/mc policy set upload myminio/insights-upload-perma;
      "

  ingress:
    image: quay.io/cloudservices/insights-ingress:latest
    ports:
      - '8080:3000'
    environment:
      - INGRESS_STAGEBUCKET=insights-upload-perma
      - INGRESS_VALIDTOPICS=playbook,playbook-sat
      - OPENSHIFT_BUILD_COMMIT=somestring
      - INGRESS_MAXSIZE=104857600
      - INGRESS_MINIODEV=true
      - INGRESS_MINIOACCESSKEY=$MINIO_ACCESS_KEY
      - INGRESS_MINIOSECRETKEY=$MINIO_SECRET_KEY
      - INGRESS_MINIOENDPOINT=minio:9000
    depends_on:
      - kafka


volumes:
  minio_conf: {}
  minio_data: {}