---
apiVersion: v1
kind: Template
metadata:
  name: storage-broker
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: storage-broker
  spec:
    envName: ${ENV_NAME}
    deployments:
    - name: processor
      minReplicas: ${{MIN_REPLICAS}}
      web: true
      podSpec:
        image: ${IMAGE_NAME}:${IMAGE_TAG}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 27
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        resources:
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
          requests:
            cpu: 250m
            memory: 64Mi
        volumeMounts:
        - mountPath: /var
          name: storage-broker-map
        volumes:
        - configMap:
            defaultMode: 420
            name: storage-broker-map
          name: storage-broker-map
        env:
          - name: CLOWDER_ENABLED
            value: ${CLOWDER_ENABLED}
          - name: LOG_LEVEL
            value: ${LOG_LEVEL}
          - name: PERM_BUCKET
            value: ${PERM_BUCKET}
          - name: REJECT_BUCKET
            value: ${REJECT_BUCKET}
    objectStore:
      - ${PERM_BUCKET}
      - ${REJECT_BUCKET}
    kafkaTopics:
      - replicas: 3
        partitions: 24
        topicName: platform.upload.validation
      - replicas: 3
        partitions: 16
        topicName: platform.upload.buckit
      - replicas: 3
        partitions: 64
        topicName: platform.upload.available
      - replicas: 3
        partitions: 64
        topicName: platform.inventory.events
      - replicas: 3
        partitions: 4
        topicName: platform.payload-status
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: storage-broker-map
  data: 
    config.yaml: |-
      platform.upload.validation:
        normalizer: Validation
      platform.upload.buckit:
        normalizer: Openshift
        services:
          openshift:
            format: "{org_id}/{cluster_id}/{timestamp}-{request_id}"
            bucket: "insights-buck-it-openshift"
          ansible:
            format: "{org_id}/{cluster_id}/{timestamp}-{request_id}"
            bucket: "insights-buck-it-ansible"
  
parameters:
- description: Minimum number of replicas required
  name: MIN_REPLICAS
  value: "1"
- description: The LOG_GROUP associated with cloudwatch
  name: LOG_GROUP
  value: platform-dev
- name: LOG_LEVEL
  value: INFO
- description: Cpu limit of service
  name: CPU_LIMIT
  value: 500m
- description: memory limit of service
  name: MEMORY_LIMIT
  value: 512Mi
- description: Image tag
  name: IMAGE_TAG
  required: true
- description: Determines Clowder deployment
  name: CLOWDER_ENABLED
  value: "true"
- description: ClowdEnv Name
  name: ENV_NAME
  value: "insights-storage-broker"
  required: true
- descripton: Insights-storage-broker image name
  name: IMAGE_NAME
  value: "quay.io/cloudservices/insights-storage-broker"
- description: Permanent Bucket
  name: PERM_BUCKET
  value: "insights-dev-upload-perm"
- description: Reject Bucket
  name: REJECT_BUCKET
  value: "insights-dev-upload-rejected"
