{
 "title": "Storage Broker",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(up{service=\"storage-broker-processor\"}[24h]))"
    }
   ]
  },
  {
   "title": "S3 Copy Errors",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(storage_broker_object_copy_error_count_total[24h])) / sum(increase(storage_broker_object_copy_success_count_total[24h])) + sum(increase(storage_broker_object_copy_error_count_total[24h]))"
    }
   ]
  },
  {
   "title": "Total Messages Consumed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(storage_broker_message_consume_count_total[1m]))",
     "legendFormat": "Messages Consumed"
    }
   ]
  },
  {
   "title": "Total Messages Published",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(storage_broker_message_publish_count_total[1m]))",
     "legendFormat": "Messages Published"
    }
   ]
  },
  {
   "title": "Total Successful Storage Copy Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(storage_broker_object_copy_success_count_total[1m]))",
     "legendFormat": "Total Storage Copy Operations"
    }
   ]
  },
  {
   "title": "Storage Copy Time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "avg(increase(storage_broker_object_copy_time_seconds_bucket[1m])) by (le)"
    }
   ]
  }
 ]
}